version: "3.2"

services:
  hackney-shared-person-test:
    image: hackney-shared-person-test
    build:
      context: .
      dockerfile: Hackney.Shared.Person.Tests/Dockerfile
      args:
        - NUGET_KEY=${NUGET_KEY}
